name: vr_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - PySide6
    - matplotlib
    - numpy
    - pandas
    - scipy
    - mne
    - mnelab
    - ipython
    - ipykernel
    - jupyter_client
    - edfio
    - pylsl
    - pyxdf
    - pybv
    - pybvrf
    - python-osc
    - onnx
    - ml_dtypes
    - requests
    - tqdm
    - black
    - isort